### ISSUE TITLE
Missing pytest-3 tool lets the build fail

### ISSUE THREAD

**Issue by astumpf** [ANYbotics/cmake_clang_tools#1]
Since the new version, the build fails due to missing pytest-3 on all machines:

https://github.com/ANYbotics/cmake_clang_tools/blob/13a66a64b9654e77c31b0c08662e191bdd302c1d/CMakeLists.txt#L78

I suggest either to extend the CMakeLists.txt either to automatically install the pytest-3 tool or at least just check if it is available on the machine. As this issue targets testing, I wonder if some kind of build flag for enabling tests would be the ideal solution, so this part can be skipped.
Otherwise it should be listed in the README as dependency.

**Comment by samuelba** [comment]
Thanks for reporting this. A fix is in progress.

**Comment by hogabrie** [comment]
Was resolved by 19cf54f1904e4c373c746f907e3f77cc8e078a24, closing.
